import os
# print(dir(os))
# print(os.getcwd())
# os.chdir("c://")
# print(os.getcwd())
# print(os.listdir("c://"))
# os.mkdir("This")
# os.makedirs("This/that")
# os.rename("khushi11.txt","harry.txt")
# print(os.environ.get('path'))
# print(os.path.join("c://","harry.txt"))
# print(os.path.exists("c://program files"))
print(os.path.isfile("c://program files"))